name: Broken Links Checker
on:
  push:
    branches:
      - Controllo_automatico_dei_link_rotti
env:
  WEBSITE_URL: "https://docusaurus-powershell.netlify.com/"
  ISSUE_TEMPLATE: ".github/workflows/check-readme-links.md"
  
permissions:
  contents: read
  issues: write 
  
jobs:
  check:
    runs-on: ubuntu-latest

    steps:
    - name: Run Broken Links Checker
      run: npx broken-link-checker $WEBSITE_URL --ordered --recursive

    - uses: actions/checkout@v3
      if: failure()

    - uses: JasonEtco/create-an-issue@v2
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        filename: ${{ env.ISSUE_TEMPLATE }}
      if: failure()
