name: Broken Links Checker
on:
  push:
    branches:
      - Controllo_automatico_dei_link_rotti
env:
  README_PATH: "README.md"
  ISSUE_TEMPLATE: ".github/workflows/ISSUE_TEMPLATE.md"
 
  contents: read
  issues: write 
  
jobs:
  build:
    name: Check if README.md links workds
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: LeandroLS/linksnitch@main  

