on:
  push:
    branches:
      - Controllo_automatico_dei_link_rotti

name: Broken Link Check
jobs:
  check:
    name: Broken Link Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Broken Link Check
        id: broken-links
        uses: technote-space/broken-link-checker-action@v2

      - name: Create Issue for Broken Links
        if: steps.broken-links.outputs.broken_links > 0
        run: |
          echo "Creating issue for broken links..."
          curl -X POST -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
          -H "Accept: application/vnd.github.v3+json" \
          https://api.github.com/repos/${{ github.repository }}/issues \
          -d '{"title":"Broken Links Detected","body":"The following broken links were detected:\n\n'$(cat broken-links.txt)'"}'
