name: Broken Links Checker
on:
  push:
    branches:
      - Controllo_automatico_dei_link_rotti
env:
  ISSUE_TEMPLATE: ".github/workflows/ISSUE_TEMPLATE.md"
 
  contents: read
  issues: write 
  
jobs:
  check:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@latest
    - name: Get links from README.md
      id: get-links
      run: |
       LINKS=$(grep -oP '\[(.*?)\]\((.*?)\)' ./README.md | sed -E 's/\[.*\]\(([^)]+)\)/\1/' | paste -sd "," -)
       echo "WEBSITE_URL=$LINKS" >> $GITHUB_ENV
      
    - name: Run Broken Links Checker
      run: | 
       BROKEN_LINKS=$(npx broken-link-checker@latest $WEBSITE_URL --ordered --recursive --filter-level error | awk '/BROKEN/ {print $4}')
       echo "BROKEN_LINKS=$BROKEN_LINKS" >> $GITHUB_ENV

    - uses: actions/checkout@latest
      if: failure()

    - uses: JasonEtco/create-an-issue@latest
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        filename: ${{ env.ISSUE_TEMPLATE }}
      if: failure()
