name: Broken Links Checker
on:
  push:
    branches:
      - Controllo_automatico_dei_link_rotti
env:
  ISSUE_TEMPLATE: ".github/workflows/ISSUE_TEMPLATE.md"
 
  contents: read
  issues: write 
  
jobs:
  check:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Get links from README.md
      id: get-links
      run: |
       LINKS=$(grep -oP '\[.*?\]\((http[s]?://[^)]*)\)' README.md | sed -E 's/\[.*\]\(([^)]+)\)/\1/' | paste -sd "," -)
       echo "WEBSITE_URL=$LINKS" >> $GITHUB_ENV
      
    - name: Run Broken Links Checker
      run: |
        BROKEN_LINKS=$(npx broken-link-checker@latest $WEBSITE_URL --ordered --recursive --filter-level error | awk '/BROKEN/ {print $4}')
        echo "BROKEN_LINKS=$BROKEN_LINKS" >> $GITHUB_ENV
        echo "Broken links found: $BROKEN_LINKS"
        if [ -n "$BROKEN_LINKS" ]; then
          echo "Broken links found, failing the workflow"
          exit 1
        fi
  

    - uses: actions/checkout@v3
      if: failure()

    - uses: JasonEtco/create-an-issue@v2
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        filename: ${{ env.ISSUE_TEMPLATE }}
      if: failure()
